services:
  mesh-controller:
    build: .
    image: mesh-controller-ihost:3.5
    network_mode: host
    restart: unless-stopped
    volumes:
      - mesh-controller-data:/data
volumes:
  mesh-controller-data:
