services:
  mesh-controller:
    build: .
    image: mesh-controller-ihost:7.0.1
    network_mode: host
    restart: unless-stopped
    volumes:
      - mesh-controller-data:/data
volumes:
  mesh-controller-data:
